INSERT INTO
    `elementos` (
        `nombre`,
        `simbolo_quimico`,
        `numero_atomico`,
        `peso_atomico`,
        `configuracion_electronica`,
        `estado_agregacion`,
        `punto_fusion`,
        `punto_ebullicion`,
        `densidad`,
        `valencia`,
        `energia_ionizacion`,
        `electronegatividad`,
        `radio_atomico`,
        `isotopos`,
        `anio_descubrimiento`,
        `descubridor`,
        `grupo_periodo`,
        `propiedades_quimicas`,
        `propiedades_fisicas`,
        `aplicaciones_principales`
    )
VALUES (
        'Hidrógeno',
        'H',
        1,
        1.008,
        '1s¹',
        'Gas',
        -259.16,
        -252.87,
        0.0899,
        '+1',
        13.5984,
        2.20,
        25,
        'Protio, Deuterio, Tritio',
        1766,
        'Henry Cavendish',
        '1, 1',
        'Es el elemento más ligero y abundante del universo. Es un gas incoloro, inodoro e insípido. Es inflamable y arde en presencia de oxígeno.',
        'Es un gas incoloro, inodoro e insípido. Es inflamable y arde en presencia de oxígeno.',
        'El hidrógeno se utiliza en la industria química para la producción de amoníaco y metanol, en la refinación de petróleo, en la producción de hidrocarburos y en la fabricación de margarina.'
    ),
    (
        'Helio',
        'He',
        2,
        4.0026,
        '1s²',
        'Gas',
        -272.20,
        -268.93,
        0.1786,
        '0',
        24.5874,
        0.00,
        31,
        'Helio-3, Helio-4',
        1895,
        'Pierre Janssen, Norman Lockyer',
        '18, 1',
        'Es el segundo elemento más ligero y se encuentra en grandes cantidades en las estrellas. Es inerte y no forma compuestos.',
        'Es un gas incoloro, inodoro, insípido y no reactivo.',
        'Se utiliza en la criogenia, en la presurización de cohetes y como gas de protección en la soldadura.'
    ),
    (
        'Litio',
        'Li',
        3,
        6.94,
        '1s² 2s¹',
        'Sólido',
        180.54,
        1342,
        0.534,
        '+1',
        5.3917,
        0.98,
        152,
        'Litio-6, Litio-7',
        1817,
        'Johan August Arfvedson',
        '1, 2',
        'Es el metal más ligero y tiene una alta capacidad de almacenamiento de energía.',
        'Es un metal blando y de color plateado, altamente reactivo con el agua.',
        'Se usa principalmente en baterías recargables y en la industria aeroespacial.'
    ),
    (
        'Berilio',
        'Be',
        4,
        9.0122,
        '1s² 2s²',
        'Sólido',
        1287,
        2469,
        1.85,
        '+2',
        9.3227,
        1.57,
        112,
        'Berilio-9',
        1798,
        'Nicholas-Louis Vauquelin',
        '2, 2',
        'Es un metal ligero pero duro, con alta resistencia a la corrosión.',
        'Es un metal grisáceo que es quebradizo a temperatura ambiente.',
        'Se utiliza en aleaciones para la industria aeroespacial, en herramientas y como moderador en reactores nucleares.'
    ),
    (
        'Boro',
        'B',
        5,
        10.81,
        '1s² 2s² 2p¹',
        'Sólido',
        2076.0,
        3927.0,
        2.34,
        '3',
        800.6,
        2.04,
        87,
        'Boro-10 (¹⁰B), Boro-11 (¹¹B)',
        1808,
        'Joseph Louis Gay-Lussac y Louis-Jacques Thénard',
        'Grupo 13, Período 2',
        'Reactivo, forma boruros con metales y compuestos con oxígeno.',
        'Sólido negro o marrón, semiconductor, cristalino o amorfo.',
        'Vidrios resistentes al calor (Pyrex), materiales compuestos, semiconductores, detergentes.'
    ),
    (
        'Nitrógeno',
        'N',
        7,
        14.007,
        '1s² 2s² 2p³',
        'Gas',
        -210.0,
        -195.8,
        0.0012506,
        '3, 5',
        1402.0,
        3.04,
        56,
        'Nitrógeno-14 (¹⁴N), Nitrógeno-15 (¹⁵N)',
        1772,
        'Daniel Rutherford',
        'Grupo 15, Período 2',
        'Forma óxidos, amoníaco, y compuestos orgánicos como aminas. Es esencial para la vida y se encuentra en el ADN y proteínas.',
        'Gas incoloro, inodoro, y constituye el 78% del aire atmosférico.',
        'Producción de amoníaco (para fertilizantes), conservación de alimentos (atmósfera inerte), criogenia (nitrógeno líquido), gas industrial para soldadura y corte.'
    );